#ifndef PRAGMAS_TTXREQS_PRAGMAS_H
#define PRAGMAS_TTXREQS_PRAGMAS_H

/*
** SAS/C / Lattice #pragma libcall for ttxreqs.library
** AUTO-GENERATED by SDK/tools/sfd_reconcile.py from ttxreqs_lib.sfd
** Do not hand-edit masks — fix the SFD and re-run the tool.
**
** Mask = register nibbles LAST→FIRST arg, then 0, then arg count.
** d0=0..d7=7 a0=8 a1=9 a2=A a3=B.  Example (a0,a1,a2,a3,d0)=0BA9805
** Wrong example: 10A9805 is (a0,a1,a2,d0,d1) — never use for a3/d0 LVOs.
** Bias 30: public LVO i is pragma offset hex(bias+6*i).
*/

#ifndef CLIB_TTXREQS_PROTOS_H
#include <clib/ttxreqs_protos.h>
#endif /* CLIB_TTXREQS_PROTOS_H */

/* No public LVOs in ttxreqs_lib.sfd yet (FuncTab = std vectors only). */

#endif /* PRAGMAS_TTXREQS_PRAGMAS_H */
