#ifndef PRAGMAS_TTXREQS_PRAGMAS_H
#define PRAGMAS_TTXREQS_PRAGMAS_H

/*
** SAS/C / Lattice #pragma libcall for ttxreqs.library
** AUTO-GENERATED by SDK/tools/sfd_reconcile.py from ttxreqs_lib.sfd
** Do not hand-edit masks — fix the SFD and re-run the tool.
**
** Mask = register nibbles LAST→FIRST arg, then 0, then arg count.
** d0=0..d7=7 a0=8 a1=9 a2=A a3=B.  Example (a0,a1,a2,a3,d0)=0BA9805
** Wrong example: 10A9805 is (a0,a1,a2,d0,d1) — never use for a3/d0 LVOs.
** Bias 30: public LVO i is pragma offset hex(bias+6*i).
*/

#ifndef CLIB_TTXREQS_PROTOS_H
#include <clib/ttxreqs_protos.h>
#endif /* CLIB_TTXREQS_PROTOS_H */

/* TR_RequestBool: SFD (a0,a1,a2) → mask A9803 offset -30 */
#pragma libcall TTXReqsBase TR_RequestBool 1E A9803
/* TR_RequestChoice: SFD (a0,a1,a2,a3) → mask BA9804 offset -36 */
#pragma libcall TTXReqsBase TR_RequestChoice 24 BA9804
/* TR_RequestStr: SFD (a0,a1,a2,a3) → mask BA9804 offset -42 */
#pragma libcall TTXReqsBase TR_RequestStr 2A BA9804
/* TR_RequestNum: SFD (a0,a1,d0,d1,a2) → mask A109805 offset -48 */
#pragma libcall TTXReqsBase TR_RequestNum 30 A109805
/* TR_RequestFile: SFD (a0,a1,d0,a2,a3) → mask BA09805 offset -54 */
#pragma libcall TTXReqsBase TR_RequestFile 36 BA09805
/* TR_RequestFind: SFD (a0,a1,a2,d0,a3) → mask B0A9805 offset -60 */
#pragma libcall TTXReqsBase TR_RequestFind 3C B0A9805
/* TR_RequestFindChange: SFD (a0,a1,a2,a3,d0,d1) → mask 10BA9806 offset -66 */
#pragma libcall TTXReqsBase TR_RequestFindChange 42 10BA9806
/* TR_PrefsSetDefaults: SFD (a0) → mask 801 offset -72 */
#pragma libcall TTXReqsBase TR_PrefsSetDefaults 48 801
/* TR_PrefsGet: SFD ((none)) → mask 000 offset -78 */
#pragma libcall TTXReqsBase TR_PrefsGet 4E 000
/* TR_PrefsSet: SFD (a0) → mask 801 offset -84 */
#pragma libcall TTXReqsBase TR_PrefsSet 54 801
/* TR_PrefsLoad: SFD (a0,a1) → mask 9802 offset -90 */
#pragma libcall TTXReqsBase TR_PrefsLoad 5A 9802
/* TR_PrefsSave: SFD (a0,a1) → mask 9802 offset -96 */
#pragma libcall TTXReqsBase TR_PrefsSave 60 9802
/* TR_PrefsRequester: SFD (a0,a1) → mask 9802 offset -102 */
#pragma libcall TTXReqsBase TR_PrefsRequester 66 9802
/* TR_InfoOpen: SFD (a0,a1) → mask 9802 offset -108 */
#pragma libcall TTXReqsBase TR_InfoOpen 6C 9802
/* TR_InfoClose: SFD (a0) → mask 801 offset -114 */
#pragma libcall TTXReqsBase TR_InfoClose 72 801
/* TR_InfoUpdate: SFD (a0,a1) → mask 9802 offset -120 */
#pragma libcall TTXReqsBase TR_InfoUpdate 78 9802
/* TR_InfoProcessMsg: SFD (a0,a1) → mask 9802 offset -126 */
#pragma libcall TTXReqsBase TR_InfoProcessMsg 7E 9802

#endif /* PRAGMAS_TTXREQS_PRAGMAS_H */
