#ifndef PRAGMAS_TURBOTEXT_PRAGMAS_H
#define PRAGMAS_TURBOTEXT_PRAGMAS_H

/*
** SAS/C / Lattice #pragma libcall for turbotext.library
** AUTO-GENERATED by SDK/tools/sfd_reconcile.py from turbotext_lib.sfd
** Do not hand-edit masks — fix the SFD and re-run the tool.
**
** Mask = register nibbles LAST→FIRST arg, then 0, then arg count.
** d0=0..d7=7 a0=8 a1=9 a2=A a3=B.  Example (a0,a1,a2,a3,d0)=0BA9805
** Wrong example: 10A9805 is (a0,a1,a2,d0,d1) — never use for a3/d0 LVOs.
** Bias 30: public LVO i is pragma offset hex(bias+6*i).
*/

#ifndef CLIB_TURBOTEXT_PROTOS_H
#include <clib/turbotext_protos.h>
#endif /* CLIB_TURBOTEXT_PROTOS_H */

/* TurboTextRun: SFD (a0,a1,a2) → mask A9803 offset -30 */
#pragma libcall TurboTextBase TurboTextRun 1E A9803
/* TT_OpenDocument: SFD (a0) → mask 801 offset -36 */
#pragma libcall TurboTextBase TT_OpenDocument 24 801
/* TT_CloseDocument: SFD (a0) → mask 801 offset -42 */
#pragma libcall TurboTextBase TT_CloseDocument 2A 801
/* TT_DoCommand: SFD (a0,a1,a2,a3,d0) → mask 0BA9805 offset -48 */
#pragma libcall TurboTextBase TT_DoCommand 30 0BA9805
/* TT_GetActiveView: SFD (a0) → mask 801 offset -54 */
#pragma libcall TurboTextBase TT_GetActiveView 36 801
/* TT_GetLastError: SFD ((none)) → mask 000 offset -60 */
#pragma libcall TurboTextBase TT_GetLastError 3C 000

#endif /* PRAGMAS_TURBOTEXT_PRAGMAS_H */
