#ifndef PROTO_TTXREQS_H
#define PROTO_TTXREQS_H

/*
** Proto header for libraries/ttxreqs.h (SAS/C pragma path).
** AUTO-GENERATED by SDK/tools/sfd_reconcile.py
*/

#ifdef _NO_INLINE

#include <clib/ttxreqs_protos.h>

#else

#ifndef __NOLIBBASE__

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library *TTXReqsBase;

#endif /* __NOLIBBASE__ */

#if defined(LATTICE) || defined(__SASC) || defined(_DCC)

#ifndef PRAGMAS_TTXREQS_PRAGMAS_H
#include <pragmas/ttxreqs_pragmas.h>
#endif

#elif defined(AZTEC_C) || defined(__MAXON__) || defined(__STORM__)

#error ttxreqs_pragmas.h not defined for this compiler

#else

#include <clib/ttxreqs_protos.h>

#endif

#endif /* _NO_INLINE */

#endif /* PROTO_TTXREQS_H */
