#ifndef PROTO_TTXSUPPORT_H
#define PROTO_TTXSUPPORT_H

/*
** Proto header for libraries/ttxsupport.h (SAS/C pragma path).
** AUTO-GENERATED by SDK/tools/sfd_reconcile.py
*/

#ifdef _NO_INLINE

#include <clib/ttxsupport_protos.h>

#else

#ifndef __NOLIBBASE__

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library *TTXSupportBase;

#endif /* __NOLIBBASE__ */

#if defined(LATTICE) || defined(__SASC) || defined(_DCC)

#ifndef PRAGMAS_TTXSUPPORT_PRAGMAS_H
#include <pragmas/ttxsupport_pragmas.h>
#endif

#elif defined(AZTEC_C) || defined(__MAXON__) || defined(__STORM__)

#error ttxsupport_pragmas.h not defined for this compiler

#else

#include <clib/ttxsupport_protos.h>

#endif

#endif /* _NO_INLINE */

#endif /* PROTO_TTXSUPPORT_H */
