#ifndef PROTO_TURBOTEXT_H
#define PROTO_TURBOTEXT_H

/*
** Proto header for libraries/turbotext.h (SAS/C pragma path).
** AUTO-GENERATED by SDK/tools/sfd_reconcile.py
*/

#ifdef _NO_INLINE

#include <clib/turbotext_protos.h>

#else

#ifndef __NOLIBBASE__

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library *TurboTextBase;

#endif /* __NOLIBBASE__ */

#if defined(LATTICE) || defined(__SASC) || defined(_DCC)

#ifndef PRAGMAS_TURBOTEXT_PRAGMAS_H
#include <pragmas/turbotext_pragmas.h>
#endif

#elif defined(AZTEC_C) || defined(__MAXON__) || defined(__STORM__)

#error turbotext_pragmas.h not defined for this compiler

#else

#include <clib/turbotext_protos.h>

#endif

#endif /* _NO_INLINE */

#endif /* PROTO_TURBOTEXT_H */
