#ifndef CLIB_TTXREQS_PROTOS_H
#define CLIB_TTXREQS_PROTOS_H

/*
** C prototypes for ttxreqs.library public LVOs.
** AUTO-GENERATED by SDK/tools/sfd_reconcile.py from ttxreqs_lib.sfd
*/

#ifdef __cplusplus
extern "C" {
#endif

#include <libraries/ttxreqs.h>

/* No public LVOs yet. */

#ifdef __cplusplus
}
#endif

#endif /* CLIB_TTXREQS_PROTOS_H */
