#ifndef CLIB_TTXSUPPORT_PROTOS_H
#define CLIB_TTXSUPPORT_PROTOS_H

/*
** C prototypes for ttxsupport.library public LVOs.
** AUTO-GENERATED by SDK/tools/sfd_reconcile.py from ttxsupport_lib.sfd
*/

#ifdef __cplusplus
extern "C" {
#endif

#include <libraries/ttxsupport.h>

/* No public LVOs yet. */

#ifdef __cplusplus
}
#endif

#endif /* CLIB_TTXSUPPORT_PROTOS_H */
