#ifndef CLIB_TURBOTEXT_PROTOS_H
#define CLIB_TURBOTEXT_PROTOS_H

/*
** C prototypes for turbotext.library public LVOs.
** AUTO-GENERATED by SDK/tools/sfd_reconcile.py from turbotext_lib.sfd
*/

#ifdef __cplusplus
extern "C" {
#endif

#include <libraries/turbotext.h>

LONG TurboTextRun(STRPTR cmdLine, struct TTUIHooks * hooks, APTR appCtx);
struct TTDocument * TT_OpenDocument(STRPTR fileName);
BOOL TT_CloseDocument(struct TTDocument * doc);
BOOL TT_DoCommand(struct TTDocument * doc, struct TTView * view, STRPTR command, STRPTR * args, ULONG argCount);
struct TTView * TT_GetActiveView(struct TTDocument * doc);
ULONG TT_GetLastError(VOID);

#ifdef __cplusplus
}
#endif

#endif /* CLIB_TURBOTEXT_PROTOS_H */
