/*
 * TTX driver - hardcoded fallback menu strip (matches TTX_BuiltIn.dfn)
 *
 * Copyright (c) 2025 amigazen project
 * Licensed under BSD 2-Clause License
 */

#include "ttx_menu_builtin.h"
#include "ttx_driver.h"

struct NewMenu TTX_BuiltinMenu[] = {
        /* Menu 0: Project */
        {NM_TITLE, "Project", NULL, 0, 0, NULL},
        {NM_ITEM, "Open...", "O", 0, 0, (APTR)TTX_MENU_UD_FLAG},
        {NM_ITEM, "Open New...", "Y", 0, 0, (APTR)((0UL << 8) | 1UL)},
        {NM_ITEM, "Insert...", NULL, 0, 0, (APTR)((0UL << 8) | 2UL)},
        {NM_ITEM, NM_BARLABEL, NULL, 0, 0, NULL},
        {NM_ITEM, "Save", "S", 0, 0, (APTR)((0UL << 8) | 4UL)},
        {NM_ITEM, "Save As...", "A", 0, 0, (APTR)((0UL << 8) | 5UL)},
        {NM_ITEM, NM_BARLABEL, NULL, 0, 0, NULL},
        {NM_ITEM, "Clear", "K", 0, 0, (APTR)((0UL << 8) | 7UL)},
        {NM_ITEM, "Print...", "P", 0, 0, (APTR)((0UL << 8) | 8UL)},
        {NM_ITEM, "Info...", "?", 0, 0, (APTR)((0UL << 8) | 9UL)},
        {NM_ITEM, NM_BARLABEL, NULL, 0, 0, NULL},
        {NM_ITEM, "Read-Only", NULL, 0, CHECKIT, (APTR)((0UL << 8) | 11UL)},
        {NM_ITEM, NM_BARLABEL, NULL, 0, 0, NULL},
        {NM_ITEM, "Close Window", "Q", 0, 0, (APTR)((0UL << 8) | 12UL)},
        
        /* Menu 1: Windows */
        {NM_TITLE, "Windows", NULL, 0, 0, NULL},
        {NM_ITEM, "New", "W", 0, 0, (APTR)((1UL << 8) | 0UL)},
        {NM_SUB, "Activate", NULL, 0, 0, NULL},
        {NM_ITEM, "Next Document", "0", 0, 0, (APTR)((1UL << 8) | 2UL)},
        {NM_ITEM, "Previous Document", "1", 0, 0, (APTR)((1UL << 8) | 3UL)},
        {NM_SUB, "Resize", NULL, 0, 0, NULL},
        {NM_ITEM, "To Maximum", NULL, 0, 0, (APTR)((1UL << 8) | 5UL)},
        {NM_ITEM, "To Minimum", NULL, 0, 0, (APTR)((1UL << 8) | 6UL)},
        {NM_ITEM, NM_BARLABEL, NULL, 0, 0, NULL},
        {NM_ITEM, "Iconify", NULL, 0, 0, (APTR)((1UL << 8) | 8UL)},
        {NM_SUB, "Organize Windows", NULL, 0, 0, NULL},
        {NM_ITEM, "Stack", NULL, 0, 0, (APTR)((1UL << 8) | 10UL)},
        {NM_ITEM, "Tile", NULL, 0, 0, (APTR)((1UL << 8) | 11UL)},
        {NM_ITEM, "Cascade", NULL, 0, 0, (APTR)((1UL << 8) | 12UL)},
        {NM_ITEM, NM_BARLABEL, NULL, 0, 0, NULL},
        {NM_ITEM, "Iconify All", NULL, 0, 0, (APTR)((1UL << 8) | 14UL)},
        {NM_SUB, "Views", NULL, 0, 0, NULL},
        {NM_ITEM, "Split", "\\", 0, 0, (APTR)((1UL << 8) | 16UL)},
        {NM_ITEM, "Toggle", "T", 0, 0, (APTR)((1UL << 8) | 17UL)},
        {NM_ITEM, "Swap", NULL, 0, 0, (APTR)((1UL << 8) | 18UL)},
        {NM_ITEM, "Expand", ";", 0, 0, (APTR)((1UL << 8) | 19UL)},
        {NM_ITEM, "Shrink", ":", 0, 0, (APTR)((1UL << 8) | 20UL)},
        {NM_ITEM, "Center", "'", 0, 0, (APTR)((1UL << 8) | 21UL)},
        {NM_ITEM, NM_BARLABEL, NULL, 0, 0, NULL},
        {NM_ITEM, "Open Hex View...", "$", 0, 0, (APTR)((1UL << 8) | 23UL)},
        {NM_ITEM, "Open Calculator...", "#", 0, 0, (APTR)((1UL << 8) | 24UL)},
        {NM_ITEM, "Open TTX Shell...", ".", 0, 0, (APTR)((1UL << 8) | 25UL)},
        {NM_ITEM, "Open DOS Shell...", NULL, 0, 0, (APTR)((1UL << 8) | 26UL)},
        {NM_ITEM, NM_BARLABEL, NULL, 0, 0, NULL},
        {NM_ITEM, "Help...", NULL, 0, 0, (APTR)((1UL << 8) | 28UL)},
        {NM_ITEM, "User's Manual...", NULL, 0, 0, (APTR)((1UL << 8) | 29UL)},
        
        /* Menu 2: Edit */
        {NM_TITLE, "Edit", NULL, 0, 0, NULL},
        {NM_ITEM, "Mark", "B", 0, 0, (APTR)((2UL << 8) | 0UL)},
        {NM_ITEM, "Cut", "X", 0, 0, (APTR)((2UL << 8) | 1UL)},
        {NM_ITEM, "Copy", "C", 0, 0, (APTR)((2UL << 8) | 2UL)},
        {NM_ITEM, "Paste", "V", 0, 0, (APTR)((2UL << 8) | 3UL)},
        {NM_ITEM, "Erase", "E", 0, 0, (APTR)((2UL << 8) | 4UL)},
        {NM_ITEM, NM_BARLABEL, NULL, 0, 0, NULL},
        {NM_ITEM, "Mark Vertical", "<", 0, 0, (APTR)((2UL << 8) | 6UL)},
        {NM_ITEM, "Paste Vertical", ">", 0, 0, (APTR)((2UL << 8) | 7UL)},
        {NM_ITEM, NM_BARLABEL, NULL, 0, 0, NULL},
        {NM_ITEM, "Open Clip...", "!", 0, 0, (APTR)((2UL << 8) | 9UL)},
        {NM_ITEM, "Save Clip As...", "@", 0, 0, (APTR)((2UL << 8) | 10UL)},
        {NM_ITEM, "Print Clip...", "&", 0, 0, (APTR)((2UL << 8) | 11UL)},
        
        /* Menu 3: Search */
        {NM_TITLE, "Search", NULL, 0, 0, NULL},
        {NM_ITEM, "Find...", "F", 0, 0, (APTR)((3UL << 8) | 0UL)},
        {NM_ITEM, "Find Next", "N", 0, 0, (APTR)((3UL << 8) | 1UL)},
        {NM_ITEM, "Find & Change...", "/", 0, 0, (APTR)((3UL << 8) | 2UL)},
        {NM_ITEM, NM_BARLABEL, NULL, 0, 0, NULL},
        {NM_ITEM, "Go To Line #...", "J", 0, 0, (APTR)((3UL << 8) | 4UL)},
        {NM_ITEM, "Go To Char #...", NULL, 0, 0, (APTR)((3UL << 8) | 5UL)},
        {NM_ITEM, "Go To Last Change", "G", 0, 0, (APTR)((3UL << 8) | 6UL)},
        {NM_ITEM, "Go To Auto-Bookmark", ",", 0, 0, (APTR)((3UL << 8) | 7UL)},
        {NM_ITEM, "Match Bracket", "[", 0, 0, (APTR)((3UL << 8) | 8UL)},
        {NM_ITEM, NM_BARLABEL, NULL, 0, 0, NULL},
        {NM_SUB, "Set Bookmark", NULL, 0, 0, NULL},
        {NM_ITEM, "#1", NULL, 0, 0, (APTR)((3UL << 8) | 11UL)},
        {NM_ITEM, "#2", NULL, 0, 0, (APTR)((3UL << 8) | 12UL)},
        {NM_ITEM, "#3", NULL, 0, 0, (APTR)((3UL << 8) | 13UL)},
        {NM_ITEM, "#4", NULL, 0, 0, (APTR)((3UL << 8) | 14UL)},
        {NM_ITEM, "#5", NULL, 0, 0, (APTR)((3UL << 8) | 15UL)},
        {NM_ITEM, "#6", NULL, 0, 0, (APTR)((3UL << 8) | 16UL)},
        {NM_ITEM, "#7", NULL, 0, 0, (APTR)((3UL << 8) | 17UL)},
        {NM_ITEM, "#8", NULL, 0, 0, (APTR)((3UL << 8) | 18UL)},
        {NM_ITEM, "#9", NULL, 0, 0, (APTR)((3UL << 8) | 19UL)},
        {NM_ITEM, "#10", NULL, 0, 0, (APTR)((3UL << 8) | 20UL)},
        {NM_SUB, "Go To Bookmark", NULL, 0, 0, NULL},
        {NM_ITEM, "#1", NULL, 0, 0, (APTR)((3UL << 8) | 22UL)},
        {NM_ITEM, "#2", NULL, 0, 0, (APTR)((3UL << 8) | 23UL)},
        {NM_ITEM, "#3", NULL, 0, 0, (APTR)((3UL << 8) | 24UL)},
        {NM_ITEM, "#4", NULL, 0, 0, (APTR)((3UL << 8) | 25UL)},
        {NM_ITEM, "#5", NULL, 0, 0, (APTR)((3UL << 8) | 26UL)},
        {NM_ITEM, "#6", NULL, 0, 0, (APTR)((3UL << 8) | 27UL)},
        {NM_ITEM, "#7", NULL, 0, 0, (APTR)((3UL << 8) | 28UL)},
        {NM_ITEM, "#8", NULL, 0, 0, (APTR)((3UL << 8) | 29UL)},
        {NM_ITEM, "#9", NULL, 0, 0, (APTR)((3UL << 8) | 30UL)},
        {NM_ITEM, "#10", NULL, 0, 0, (APTR)((3UL << 8) | 31UL)},
        
        /* Menu 4: Macros */
        {NM_TITLE, "Macros", NULL, 0, 0, NULL},
        {NM_ITEM, "Record Macro", "R", 0, 0, (APTR)((4UL << 8) | 0UL)},
        {NM_ITEM, "Stop Recording", "H", 0, 0, (APTR)((4UL << 8) | 1UL)},
        {NM_ITEM, "Play Macro", "M", 0, 0, (APTR)((4UL << 8) | 2UL)},
        {NM_ITEM, "Play Many...", "I", 0, 0, (APTR)((4UL << 8) | 3UL)},
        {NM_ITEM, NM_BARLABEL, NULL, 0, 0, NULL},
        {NM_ITEM, "Open Macro...", "2", 0, 0, (APTR)((4UL << 8) | 5UL)},
        {NM_ITEM, "Save Macro As...", NULL, 0, 0, (APTR)((4UL << 8) | 6UL)},
        {NM_ITEM, NM_BARLABEL, NULL, 0, 0, NULL},
        {NM_ITEM, "Execute ARexx...", "3", 0, 0, (APTR)((4UL << 8) | 8UL)},
        
        /* Menu 5: Folds */
        {NM_TITLE, "Folds", NULL, 0, 0, NULL},
        {NM_ITEM, "Make Fold", "(", 0, 0, (APTR)((5UL << 8) | 0UL)},
        {NM_ITEM, NM_BARLABEL, NULL, 0, 0, NULL},
        {NM_SUB, "Show", NULL, 0, 0, NULL},
        {NM_ITEM, "Single", "+", 0, 0, (APTR)((5UL << 8) | 3UL)},
        {NM_ITEM, "Nested", NULL, 0, 0, (APTR)((5UL << 8) | 4UL)},
        {NM_ITEM, "All", NULL, 0, 0, (APTR)((5UL << 8) | 5UL)},
        {NM_SUB, "Hide", NULL, 0, 0, NULL},
        {NM_ITEM, "Single", "-", 0, 0, (APTR)((5UL << 8) | 7UL)},
        {NM_ITEM, "Nested", NULL, 0, 0, (APTR)((5UL << 8) | 8UL)},
        {NM_ITEM, "All", NULL, 0, 0, (APTR)((5UL << 8) | 9UL)},
        {NM_SUB, "Unmake", NULL, 0, 0, NULL},
        {NM_ITEM, "Single", ")", 0, 0, (APTR)((5UL << 8) | 11UL)},
        {NM_ITEM, "Nested", NULL, 0, 0, (APTR)((5UL << 8) | 12UL)},
        {NM_ITEM, "All", NULL, 0, 0, (APTR)((5UL << 8) | 13UL)},
        
        /* Menu 6: Extras */
        {NM_TITLE, "Extras", NULL, 0, 0, NULL},
        {NM_ITEM, "Undelete Line", "D", 0, 0, (APTR)((6UL << 8) | 0UL)},
        {NM_ITEM, "Undo Line", "Z", 0, 0, (APTR)((6UL << 8) | 1UL)},
        {NM_ITEM, NM_BARLABEL, NULL, 0, 0, NULL},
        {NM_ITEM, "Center", "^", 0, 0, (APTR)((6UL << 8) | 3UL)},
        {NM_ITEM, "Justify", "=", 0, 0, (APTR)((6UL << 8) | 4UL)},
        {NM_ITEM, "Format Paragraph", "]", 0, 0, (APTR)((6UL << 8) | 5UL)},
        {NM_ITEM, NM_BARLABEL, NULL, 0, 0, NULL},
        {NM_ITEM, "Convert To Upper Case", "U", 0, 0, (APTR)((6UL << 8) | 7UL)},
        {NM_ITEM, "Convert To Lower Case", "L", 0, 0, (APTR)((6UL << 8) | 8UL)},
        {NM_ITEM, "Convert Tabs To Spaces", NULL, 0, 0, (APTR)((6UL << 8) | 9UL)},
        
        /* Menu 7: Prefs */
        {NM_TITLE, "Prefs", NULL, 0, 0, NULL},
        {NM_ITEM, "Change...", "4", 0, 0, (APTR)((7UL << 8) | 0UL)},
        {NM_ITEM, NM_BARLABEL, NULL, 0, 0, NULL},
        {NM_ITEM, "Open Prefs...", NULL, 0, 0, (APTR)((7UL << 8) | 2UL)},
        {NM_ITEM, "Save Prefs As...", NULL, 0, 0, (APTR)((7UL << 8) | 3UL)},
        {NM_ITEM, "Save As Defaults", NULL, 0, 0, (APTR)((7UL << 8) | 4UL)},
        {NM_ITEM, NM_BARLABEL, NULL, 0, 0, NULL},
        {NM_ITEM, "Open Definitions...", NULL, 0, 0, (APTR)((7UL << 8) | 6UL)},
        
        /* End marker */
        {NM_END, NULL, NULL, 0, 0, NULL}
};
